# Generated by Django 4.0.1 on 2022-12-30 10:36
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0005_create_new_objects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goalcategory",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="goals.board",
                verbose_name="Доска",
            ),
        ),
    ]
